import Head from "next/head";
import styles from "~/styles/Home.module.css";
import useSWR from "swr";
import { GetServerSideProps } from "next";
import axios from "axios";

const getURL = (pokemon?: string | string[]) => `https://pokeapi.co/api/v2/pokemon/${pokemon}`;

interface Pokemon {
    sprites: {
        front_default: string;
    };
    types: {
        type: {
            name: string;
        };
    }[];
    height: string;
    weight: string;
}

interface PageProps {
    pokemon?: string | string[];
    fallbackData: Pokemon;
}

export const getServerSideProps: GetServerSideProps<PageProps> = async ({ params }) => {
    const data = await axios.get(getURL(params?.pokemon)).then((res) => res.data);
    return {
        props: {
            fallbackData: data,
            pokemon: params?.pokemon,
        },
    };
};

export default function Home(props: PageProps) {
    const { pokemon, fallbackData } = props;
    const { data } = useSWR<Pokemon>(getURL(pokemon), { fallbackData });
    return (
        <>
            <Head>
                <title>Pokemon</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.container}>
                <h1 className="text-3xl font-bold underline">Pokemon: {pokemon}</h1>
                {data ? (
                    <div>
                        <p>Height: {data.height}</p>
                        <p>Weight: {data.weight}</p>
                        <ul>
                            Types: {data.types.map(({ type }) => (
                                <li key={type.name}>{type.name}</li>
                            ))}
                        </ul>
                    </div>
                ) : (
                    "loading..."
                )}
            </div>
        </>
    );
}
